# Generated by Django 4.0.6 on 2022-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PhoneTable',
        ),
    ]
